// Parse the OCR text file already generated by extract-ocr.mjs
// Each record is on a single line in the format:
// CPE NOME NIPC RUA NUMERO [COMPLEMENT] POSTAL LOCALIDADE CAE DATA NIVEL TIPO CMA

import fs from 'fs';

const OCR_PATH = 'C:/Users/Utilizador/Downloads/ocr-full.txt';
const OUT_PATH = 'C:/Users/Utilizador/Downloads/instalacoes.csv';

function q(str) {
  return `"${String(str || '').trim().replace(/"/g, '""')}"`;
}

function parseDate(str) {
  const m = str && str.match(/(\d{2})-(\d{2})-(\d{4})/);
  return m ? `${m[3]}-${m[2]}-${m[1]}` : '';
}

// Fix common OCR substitutions in CPE/NIPC codes
function fixOcr(str) {
  return str.replace(/[oO]/g, '0');
}

const cpeFullRe   = /\bPT[A-Z0-9]{14,22}\b/gi;
const nipcFullRe  = /\bPT[A-Z0-9E]{9}\b/gi;  // PT + 9 chars (PT500... or PTE80...)
const postalRe    = /\b(\d{4}-\d{3})\b/;
const dateRe      = /\b(\d{2}-\d{2}-\d{4})\b/;
const nivelRe     = /\b(MAT|MT|BTE|BTN|AT)\b/;
const cmaEndRe    = /\b(\d+)\s*$/;

const text = fs.readFileSync(OCR_PATH, 'utf8');
const lines = text.split('\n').map(l => l.trim()).filter(l => l.length > 5);

const records = [];

for (const line of lines) {
  // A record line must contain a CPE-like code at or near the start
  const cpeMatch = line.match(/^(PT[A-Z0-9]{14,22})\s/i);
  if (!cpeMatch) continue;

  const cpe = fixOcr(cpeMatch[1]).toUpperCase();

  // Extract postal code
  const postalMatch = line.match(postalRe);
  const codPostal = postalMatch ? postalMatch[1] : '';

  // Extract date
  const dateMatch = line.match(dateRe);
  const dataInicio = dateMatch ? parseDate(dateMatch[1]) : '';

  // Extract nivel tensao
  const nivelMatch = line.match(nivelRe);
  const nivelTensao = nivelMatch ? nivelMatch[1] : '';

  // Extract CMA: last number at end of line (before optional trailing whitespace)
  const cmaMatch = line.match(cmaEndRe);
  const cma = cmaMatch ? cmaMatch[1] : '';

  // Find NIPC: PT + exactly 9 alphanumeric chars (shorter than CPE)
  // Remove the CPE first to avoid confusion
  const withoutCpe = line.slice(cpeMatch[0].length);
  const nipcMatch = withoutCpe.match(/\b(PT[A-Z0-9]{9})\b/i);
  const nipc = nipcMatch ? fixOcr(nipcMatch[1]).toUpperCase() : '';

  // Nome: text between CPE and NIPC
  let nome = '';
  if (nipcMatch && nipcMatch.index !== undefined) {
    nome = withoutCpe.slice(0, nipcMatch.index).trim().replace(/\s+/g, ' ');
  }

  // Address: text between NIPC and postal code
  let rua = '', porta = '', descPostal = '';
  if (nipcMatch && postalMatch) {
    const afterNipc = withoutCpe.slice(nipcMatch.index + nipcMatch[1].length);
    const postalIdx = afterNipc.indexOf(codPostal);
    if (postalIdx > 0) {
      const addrRaw = afterNipc.slice(0, postalIdx).trim().replace(/\s+/g, ' ');
      // Split address: last token(s) are likely porta/complement, first part is rua
      // Common separators in data: number after street name
      const addrMatch = addrRaw.match(/^(.*?)\s+(\d+\S*)\s*(.*?)$/);
      if (addrMatch) {
        rua   = addrMatch[1].trim();
        porta = addrMatch[2].trim();
        const rest = addrMatch[3].trim();
        // rest might be andar/complement or junk (--), filter out dashes
        if (rest && !/^-+$/.test(rest) && rest.length > 1) {
          porta += ' ' + rest;
        }
      } else {
        rua = addrRaw;
      }
    }
    // Locality: text after postal code up to the CAE number
    const afterPostal = afterNipc.slice(postalIdx + codPostal.length).trim();
    const localMatch = afterPostal.match(/^([A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ][A-ZÁÉÍÓÚÂÊÎÔÛÃÕÀÈÌÒÙÇ\s]+)/i);
    descPostal = localMatch ? localMatch[1].trim() : '';
  }

  records.push({ cpe, nipc, nome, rua, porta, andar: '', codPostal, descPostal, dataInicio, nivelTensao, cma });
}

console.log(`Parsed ${records.length} records`);
if (records[0]) console.log('Sample 1:', JSON.stringify(records[0]));
if (records[1]) console.log('Sample 2:', JSON.stringify(records[1]));
if (records[5]) console.log('Sample 6:', JSON.stringify(records[5]));

if (records.length > 0) {
  const header = 'CPE,NIPC,Nome,Rua,Porta,Andar_Fracao,Cod_Postal,Desc_Postal,Inicio_Contrato,Nivel_Tensao,CMA_kWh\n';
  const rows = records.map(r =>
    [q(r.cpe), q(r.nipc), q(r.nome), q(r.rua), q(r.porta), q(r.andar),
     q(r.codPostal), q(r.descPostal), q(r.dataInicio), q(r.nivelTensao), q(r.cma)].join(',')
  );
  fs.writeFileSync(OUT_PATH, '\uFEFF' + header + rows.join('\n'), 'utf8');
  console.log('\nCSV saved to:', OUT_PATH);
} else {
  console.log('No records found.');
}
